#define nop_100 \
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
__asm__ __volatile__("nop");\
